### ISSUE TITLE
Javascript error for suppressing notification

### ISSUE THREAD

**Issue by timmmmyboy** [pgogy/WordPress-Fewster#1]
Clicking this link does nothing, javascript doesn't appear to be enqueuing properly in the console

<img width="650" alt="screen shot 2017-04-27 at 10 05 17 am" src="https://cloud.githubusercontent.com/assets/3890972/25487322/dadbf360-2b31-11e7-87a4-72f7f69c012a.png">

**Comment by timmmmyboy** [comment]
This may be possibly related but these integrity check links don't do anything for me either

<img width="597" alt="screen shot 2017-04-27 at 10 04 12 am" src="https://cloud.githubusercontent.com/assets/3890972/25487361/00d68ce2-2b32-11e7-93f5-b46cf48531dd.png">

**Comment by pgogy** [comment]
Screen dump of console?

**Comment by timmmmyboy** [comment]
Ah, figured it out. The code is requiring that the plugin folder be called fewster. I cloned the repo which named the folder WordPress-Fewster. Renaming fixed all this.

**Comment by pgogy** [comment]
ah I should fix that

**Comment by pgogy** [comment]
Latest code commit should fix this and neaten some stuff up
